# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PROJECT_NAME: "Sample Application"
  REPO_PATH: "/home/ajad/Music/Azure"
  PYTHON_PATH: "/usr/bin/python3"
  PYTEST_PATH: "/usr/bin/pytest"

stages:
- stage: CloneRepository
  displayName: "Stage 1: Clone Repository"
  jobs:
  - job: CloneRepo
    steps:
    - script: |
        echo "Project Name: $(PROJECT_NAME)"
        git clone https://github.com/ajadlitan/GreenCodeSQLite.git $(REPO_PATH)
        chmod -R 777 $(REPO_PATH)
      displayName: "Clone Repository"

- stage: TrackServerEmissions
  displayName: "Stage 2: Track Server Emissions"
  jobs:
  - job: TrackEmissions
    steps:
    - script: |
        cd $(REPO_PATH)
        $(PYTHON_PATH) server_emissions.py || exit 1
      displayName: "Run server_emissions.py"

- stage: GreenCodeRefiner
  displayName: "Stage 3: Green Code Refiner"
  jobs:
  - job: RefineCode
    steps:
    - script: |
        cd $(REPO_PATH)
        $(PYTHON_PATH) GreenCodeRefiner.py || exit 1
      displayName: "Run GreenCodeRefiner.py"

- stage: DynamicCodeAnalysis
  displayName: "Stage 4: Dynamic Code Analysis & Report Generate"
  jobs:
  - job: AnalyzeCode
    steps:
    - script: |
        cd $(REPO_PATH)
        $(PYTHON_PATH) track_emissions.py || exit 1
      displayName: "Run track_emissions.py"

